# Sync tasks from docs/tasks/ to GitHub Issues
# Powered by 5DayDocs: https://github.com/jnun/5daydocs
#
# This workflow calls the 5DayDocs reusable workflow.
# All logic is maintained in the 5DayDocs repository - you just get updates automatically.

name: Sync Tasks to Issues

on:
  push:
    paths:
      - 'docs/tasks/**/*.md'
      - 'docs/STATE.md'
    branches:
      - main
  workflow_dispatch:
    inputs:
      force_sync_all:
        description: 'Force sync all tasks'
        type: boolean
        default: false

jobs:
  sync:
    uses: jnun/5daydocs/.github/workflows/sync-tasks-reusable.yml@main
    with:
      tasks_path: 'docs/tasks'
      state_file: 'docs/STATE.md'
      force_sync_all: ${{ inputs.force_sync_all || false }}
      # Optional: GitHub Projects integration
      # Uncomment and configure to sync tasks to a GitHub Project board
      # project_number: '1'
      # project_owner: 'your-username-or-org'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      # Uncomment if using GitHub Projects (requires PAT with project scope)
      # project_token: ${{ secrets.GH_PROJECT_TOKEN }}
